version: 2

builds:
  - id: webhook
    main: ./cmd/webhook
    binary: external-dns-vultr-webhook
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

dockers_v2:
  - ids: [webhook]
    dockerfile: Dockerfile
    images: ["vultr/external-dns-vultr-webhook"]
    tags: ["{{ .Tag }}", "latest"]
    platforms: ["linux/amd64", "linux/arm64"]
    labels:
      org.opencontainers.image.source: "https://github.com/Vultr/external-dns-vultr-webhook"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "Apache-2.0"

release:
  github:
    owner: Vultr
    name: external-dns-vultr-webhook
