name: notify-pr

on: pull_request_target

jobs:
  pr:
    uses: vultr/shared-actions/.github/workflows/notify-pr.yml@0bd6842999b6890065117e596dd12ab4fdba410f
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      pr_number: ${{ github.event.number }}
