name: AI PR Review
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    uses: vultr/shared-actions/.github/workflows/review.yml@0bd6842999b6890065117e596dd12ab4fdba410f
    secrets: inherit
